//MAINCATEGORY
export const CREATE_MAINCATEGORY = "CREATE_MAINCATEGORY"
export const CREATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED"
export const GET_MAINCATEGORY = "GET_MAINCATEGORY"
export const GET_MAINCATEGORY_RED = "GET_MAINCATEGORY_RED"
export const UDPATE_MAINCATEGORY = "UDPATE_MAINCATEGORY"
export const UDPATE_MAINCATEGORY_RED = "UDPATE_MAINCATEGORY_RED"
export const DELETE_MAINCATEGORY = "DELETE_MAINCATEGORY"
export const DELETE_MAINCATEGORY_RED = "DELETE_MAINCATEGORY_RED"

//SUBCATEGORY
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY"
export const CREATE_SUBCATEGORY_RED = "CREATE_SUBCATEGORY_RED"
export const GET_SUBCATEGORY = "GET_SUBCATEGORY"
export const GET_SUBCATEGORY_RED = "GET_SUBCATEGORY_RED"
export const UDPATE_SUBCATEGORY = "UDPATE_SUBCATEGORY"
export const UDPATE_SUBCATEGORY_RED = "UDPATE_SUBCATEGORY_RED"
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY"
export const DELETE_SUBCATEGORY_RED = "DELETE_SUBCATEGORY_RED"

//BRAND
export const CREATE_BRAND = "CREATE_BRAND"
export const CREATE_BRAND_RED = "CREATE_BRAND_RED"
export const GET_BRAND = "GET_BRAND"
export const GET_BRAND_RED = "GET_BRAND_RED"
export const UDPATE_BRAND = "UDPATE_BRAND"
export const UDPATE_BRAND_RED = "UDPATE_BRAND_RED"
export const DELETE_BRAND = "DELETE_BRAND"
export const DELETE_BRAND_RED = "DELETE_BRAND_RED"

//PRODUCT
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const CREATE_PRODUCT_RED = "CREATE_PRODUCT_RED"
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_RED = "GET_PRODUCT_RED"
export const UDPATE_PRODUCT = "UDPATE_PRODUCT"
export const UDPATE_PRODUCT_RED = "UDPATE_PRODUCT_RED"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_RED = "DELETE_PRODUCT_RED"

//FEATURE
export const CREATE_FEATURE = "CREATE_FEATURE"
export const CREATE_FEATURE_RED = "CREATE_FEATURE_RED"
export const GET_FEATURE = "GET_FEATURE"
export const GET_FEATURE_RED = "GET_FEATURE_RED"
export const UDPATE_FEATURE = "UDPATE_FEATURE"
export const UDPATE_FEATURE_RED = "UDPATE_FEATURE_RED"
export const DELETE_FEATURE = "DELETE_FEATURE"
export const DELETE_FEATURE_RED = "DELETE_FEATURE_RED"

//FAQ
export const CREATE_FAQ = "CREATE_FAQ"
export const CREATE_FAQ_RED = "CREATE_FAQ_RED"
export const GET_FAQ = "GET_FAQ"
export const GET_FAQ_RED = "GET_FAQ_RED"
export const UDPATE_FAQ = "UDPATE_FAQ"
export const UDPATE_FAQ_RED = "UDPATE_FAQ_RED"
export const DELETE_FAQ = "DELETE_FAQ"
export const DELETE_FAQ_RED = "DELETE_FAQ_RED"

//SETTING
export const CREATE_SETTING = "CREATE_SETTING"
export const CREATE_SETTING_RED = "CREATE_SETTING_RED"
export const GET_SETTING = "GET_SETTING"
export const GET_SETTING_RED = "GET_SETTING_RED"
export const UDPATE_SETTING = "UDPATE_SETTING"
export const UDPATE_SETTING_RED = "UDPATE_SETTING_RED"
export const DELETE_SETTING = "DELETE_SETTING"
export const DELETE_SETTING_RED = "DELETE_SETTING_RED"

//CART
export const CREATE_CART = "CREATE_CART"
export const CREATE_CART_RED = "CREATE_CART_RED"
export const GET_CART = "GET_CART"
export const GET_CART_RED = "GET_CART_RED"
export const UDPATE_CART = "UDPATE_CART"
export const UDPATE_CART_RED = "UDPATE_CART_RED"
export const DELETE_CART = "DELETE_CART"
export const DELETE_CART_RED = "DELETE_CART_RED"

//WISHLIST
export const CREATE_WISHLIST = "CREATE_WISHLIST"
export const CREATE_WISHLIST_RED = "CREATE_WISHLIST_RED"
export const GET_WISHLIST = "GET_WISHLIST"
export const GET_WISHLIST_RED = "GET_WISHLIST_RED"
export const UDPATE_WISHLIST = "UDPATE_WISHLIST"
export const UDPATE_WISHLIST_RED = "UDPATE_WISHLIST_RED"
export const DELETE_WISHLIST = "DELETE_WISHLIST"
export const DELETE_WISHLIST_RED = "DELETE_WISHLIST_RED"

//CHECKOUT
export const CREATE_CHECKOUT = "CREATE_CHECKOUT"
export const CREATE_CHECKOUT_RED = "CREATE_CHECKOUT_RED"
export const GET_CHECKOUT = "GET_CHECKOUT"
export const GET_CHECKOUT_RED = "GET_CHECKOUT_RED"
export const UDPATE_CHECKOUT = "UDPATE_CHECKOUT"
export const UDPATE_CHECKOUT_RED = "UDPATE_CHECKOUT_RED"
export const DELETE_CHECKOUT = "DELETE_CHECKOUT"
export const DELETE_CHECKOUT_RED = "DELETE_CHECKOUT_RED"

//NEWSLETTER
export const CREATE_NEWSLETTER = "CREATE_NEWSLETTER"
export const CREATE_NEWSLETTER_RED = "CREATE_NEWSLETTER_RED"
export const GET_NEWSLETTER = "GET_NEWSLETTER"
export const GET_NEWSLETTER_RED = "GET_NEWSLETTER_RED"
export const UDPATE_NEWSLETTER = "UDPATE_NEWSLETTER"
export const UDPATE_NEWSLETTER_RED = "UDPATE_NEWSLETTER_RED"
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER"
export const DELETE_NEWSLETTER_RED = "DELETE_NEWSLETTER_RED"

//CONTACT_US
export const CREATE_CONTACT_US = "CREATE_CONTACT_US"
export const CREATE_CONTACT_US_RED = "CREATE_CONTACT_US_RED"
export const GET_CONTACT_US = "GET_CONTACT_US"
export const GET_CONTACT_US_RED = "GET_CONTACT_US_RED"
export const UDPATE_CONTACT_US = "UDPATE_CONTACT_US"
export const UDPATE_CONTACT_US_RED = "UDPATE_CONTACT_US_RED"
export const DELETE_CONTACT_US = "DELETE_CONTACT_US"
export const DELETE_CONTACT_US_RED = "DELETE_CONTACT_US_RED"

//TESTIMONIAL
export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL"
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED"
export const GET_TESTIMONIAL = "GET_TESTIMONIAL"
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED"
export const UDPATE_TESTIMONIAL = "UDPATE_TESTIMONIAL"
export const UDPATE_TESTIMONIAL_RED = "UDPATE_TESTIMONIAL_RED"
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL"
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED"

//USER
export const CREATE_USER = "CREATE_USER"
export const CREATE_USER_RED = "CREATE_USER_RED"
export const GET_USER = "GET_USER"
export const GET_USER_RED = "GET_USER_RED"
export const UDPATE_USER = "UDPATE_USER"
export const UDPATE_USER_RED = "UDPATE_USER_RED"
export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_RED = "DELETE_USER_RED"

